name: Markerup
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: "13.0"
settings:
  ENABLE_USER_SCRIPT_SANDBOXING: NO
targets:
  Markerup:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    info:
      path: Info.plist
    sources: []
    postCompileScripts:
      - name: Build Rust executable
        script: ./build_for_ios_with_cargo.sh markerup
        basedOnDependencyAnalysis: false
